import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

const fallbackOperations = [
  { id:"NW_RECONCILIATION", name:"Network Reconciliation", description:"Compare network CMDB records against current IS inventory." },
  { id:"SERVER_RECONCILIATION", name:"Server Reconciliation", description:"Identify server inventory gaps and required IS updates." },
  { id:"HARDWARE_GOVERNANCE", name:"Hardware Governance", description:"Resolve physical devices against the authoritative IS hardware catalog." },
  { id:"OS_BULK_LOAD", name:"OS Bulk Governance", description:"Validate operating-system candidates before controlled load generation." }
];

function Icon({name}) {
  const p={grid:"M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z",home:"M3 11 12 3l9 8M5 10v10h14V10M9 20v-6h6v6",shield:"M12 3 20 7v5c0 5-3.5 8.5-8 10-4.5-1.5-8-5-8-10V7z",activity:"M3 12h4l2-7 4 14 2-7h6",database:"M4 6c0-2 3.6-3 8-3s8 1 8 3-3.6 3-8 3-8-1-8-3Zm0 0v6c0 2 3.6 3 8 3s8-1 8-3V6",layers:"m12 3 9 5-9 5-9-5zM3 12l9 5 9-5M3 16l9 5 9-5",clock:"M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0",alert:"M12 4 3 20h18zM12 9v5m0 3h.01",check:"m5 12 4 4L19 6",arrow:"M5 12h14m-6-6 6 6-6 6",search:"m20 20-4.5-4.5M10.5 18a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15",settings:"M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm0-5v2m0 14v2m9-9h-2M5 12H3",plus:"M12 5v14M5 12h14"};
  return <svg viewBox="0 0 24 24"><path d={p[name]||p.grid}/></svg>;
}
const Badge=({children,tone="neutral"})=><span className={"badge "+tone}>{children}</span>;

async function getJSON(path){
  const r=await fetch(path);
  if(!r.ok) throw new Error(path+" "+r.status);
  return r.json();
}

function Sidebar({active,setActive,health}){
 const nav=[["overview","Overview","home"],["governance","Governance","shield"],["reconciliation","Reconciliation","layers"],["jobs","Jobs & runs","clock"],["exceptions","Exceptions","alert"],["audit","Audit & evidence","database"]];
 return <aside className="sidebar">
  <div className="brand"><div className="brand-mark"><Icon name="grid"/></div><div><strong>Reconciliation</strong><span>Recommendation Platform</span></div></div>
  <div className="app-selector"><div className="eyebrow">ACTIVE APPLICATION</div><div className="app-name"><span className="status-dot"/> CMDB & IS Governance</div><Badge tone="active">LOCAL EDITION</Badge></div>
  <nav>{nav.map(([id,label,icon])=><button key={id} className={active===id?"nav-item selected":"nav-item"} onClick={()=>setActive(id)}><Icon name={icon}/><span>{label}</span></button>)}</nav>
  <div className="sidebar-bottom"><div className="environment"><span className={"status-dot"}/> Engine {health?.status==="READY"?"ready":"offline"} <small>V{health?.golden_version||"1.4.1"}</small></div><button className="nav-item"><Icon name="settings"/><span>Settings</span></button></div>
 </aside>;
}

function Header({active,health}){
 return <header className="header"><div className="crumb">CMDB & IS Governance <span>/</span> {active.replaceAll("-"," ")}</div><div className="header-actions"><div className="search"><Icon name="search"/><span>Search assets, jobs, evidence...</span><kbd>⌘ K</kbd></div><div className="user"><div className="avatar">VV</div><div><strong>Governance Admin</strong><small>Local identity · {health?.version||"connecting"}</small></div></div></div></header>;
}

function Overview({setActive,operations,health}){
 return <div className="page">
  <div className="page-heading"><div><div className="eyebrow">ENTERPRISE GOVERNANCE</div><h1>Governance overview</h1><p>Monitor reconciliation health, catalog compliance and controlled inventory actions.</p></div><button className="primary" onClick={()=>setActive("reconciliation")}><Icon name="plus"/> New governance run</button></div>
  <div className="stats"><div className="stat-card"><div className="stat-top"><span>Engine status</span><Icon name="check"/></div><div className="stat-value">{health?.status||"CONNECTING"}</div><div className="stat-delta">Business engine V{health?.golden_version||"1.4.1"}</div></div><div className="stat-card"><div className="stat-top"><span>Application</span><Icon name="shield"/></div><div className="stat-value">ACTIVE</div><div className="stat-delta">CMDB & IS Governance</div></div><div className="stat-card"><div className="stat-top"><span>Operations</span><Icon name="activity"/></div><div className="stat-value">{operations.length}</div><div className="stat-delta">Governance capabilities exposed</div></div><div className="stat-card"><div className="stat-top"><span>Execution mode</span><Icon name="database"/></div><div className="stat-value">LOCAL</div><div className="stat-delta">Offline-capable core processing</div></div></div>
  <div className="grid-main"><section className="panel"><div className="panel-head"><div><h2>Platform posture</h2><p>Live state from the FastAPI application boundary.</p></div><Badge tone={health?.status==="READY"?"good":"review"}>{health?.status||"CONNECTING"}</Badge></div><div className="posture"><div className="donut"><div><strong>{health?.golden_version||"1.4.1"}</strong><span>golden engine</span></div></div><div className="legend"><div><span className="dot load"/><strong>Application</strong><b>V{health?.version||"—"}</b></div><div><span className="dot review"/><strong>Mode</strong><b>{health?.mode||"—"}</b></div><div><span className="dot block"/><strong>Transport</strong><b>FastAPI</b></div></div></div></section>
  <section className="panel"><div className="panel-head"><div><h2>Architecture boundary</h2><p>UI never imports the business engine directly.</p></div></div><div className="run-list"><div className="run-row"><div className="run-icon"><Icon name="layers"/></div><div className="run-info"><strong>React / Vite</strong><small>Enterprise presentation layer</small></div><Badge tone="good">READY</Badge></div><div className="run-row"><div className="run-icon"><Icon name="activity"/></div><div className="run-info"><strong>FastAPI</strong><small>Application transport boundary</small></div><Badge tone="good">READY</Badge></div><div className="run-row"><div className="run-icon"><Icon name="shield"/></div><div className="run-info"><strong>V1.4.1 Golden Engine</strong><small>Business behavior preserved</small></div><Badge tone="good">PROTECTED</Badge></div></div></section></div>
  <section className="panel"><div className="panel-head"><div><h2>Governance workspaces</h2><p>Capabilities are sourced from the API rather than duplicated in the UI.</p></div></div><div className="operation-grid">{operations.map((o,i)=><button className="operation" key={o.id} onClick={()=>setActive("reconciliation")}><div className="operation-icon"><Icon name={i===3?"shield":i===2?"database":"layers"}/></div><div><strong>{o.name}</strong><p>{o.description}</p><span>Open workspace <Icon name="arrow"/></span></div></button>)}</div></section>
 </div>;
}

async function postJSON(path,body){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json();}

function Jobs({jobs,setJobs}){const refresh=()=>fetch("/api/jobs").then(r=>r.json()).then(x=>setJobs(x.items||[]));useEffect(()=>{refresh();const t=setInterval(refresh,1200);return()=>clearInterval(t)},[]);return <div className="page"><div className="page-heading"><div><div className="eyebrow">PLATFORM OPERATIONS</div><h1>Jobs & runs</h1><p>Track execution state, progress, failures and result summaries.</p></div><Badge tone="active">LOCAL WORKER</Badge></div><section className="panel table-panel"><div className="toolbar"><div><strong style={{fontSize:12}}>Execution history</strong><div style={{fontSize:9,color:"#98a2b3",marginTop:3}}>State is persisted locally for restart visibility.</div></div><button className="ghost" onClick={refresh}><Icon name="activity"/> Refresh</button></div><table><thead><tr><th>Job</th><th>Operation</th><th>Status</th><th>Progress</th><th>Message</th><th>Created</th></tr></thead><tbody>{jobs.length?jobs.map(j=><tr key={j.job_id}><td><strong>{j.job_id}</strong><small>{j.actor}</small></td><td>{j.operation}</td><td><Badge tone={j.status==="COMPLETED"?"good":j.status==="FAILED"?"block":j.status==="RUNNING"?"review":"muted"}>{j.status}</Badge></td><td>{j.progress}%</td><td>{j.error||j.message}</td><td>{new Date(j.created_at).toLocaleString()}</td></tr>):<tr><td colSpan="6">No governance jobs have been submitted yet.</td></tr>}</tbody></table></section></div>}

function ResourceInput({item,onUploaded,existing}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const upload=async(e)=>{ const file=e.target.files?.[0]; if(!file)return; setBusy(true);setError(""); try{ const form=new FormData();form.append("kind",item.kind);form.append("file",file); const r=await fetch("/api/resources/upload",{method:"POST",body:form}); const data=await r.json(); if(!r.ok)throw new Error(data.detail||"Upload failed"); onUploaded(item.kind,data); }catch(err){setError(err.message)}finally{setBusy(false);e.target.value=""} };
 const current=existing?.[item.kind];
 return <div className="resource-card"><div className="resource-card-head"><div><strong>{item.label}</strong><small>{item.description}</small></div><Badge tone={current?"good":"review"}>{current?"LOADED":"REQUIRED"}</Badge></div>{current&&<div className="resource-loaded"><Icon name="check"/><span>{current.filename||current.file_name}</span><small>{current.size!=null?Math.round(current.size/1024)+" KB":""}</small></div>}<label className="upload-button"><Icon name="plus"/>{busy?"Uploading...":current?"Replace file":"Load file"}<input type="file" accept={item.extensions.join(",")} disabled={busy} onChange={upload}/></label>{error&&<div className="upload-error">{error}</div>}</div>;
}

function Reconciliation({operations,setActive}){
 const [selected,setSelected]=useState(operations[0]?.id||"NW_RECONCILIATION");
 const [domain,setDomain]=useState("network"),[resources,setResources]=useState({}),[resourceRecords,setResourceRecords]=useState({}),[available,setAvailable]=useState([]),[required,setRequired]=useState([]),[missing,setMissing]=useState([]),[checking,setChecking]=useState(false),[starting,setStarting]=useState(false),[error,setError]=useState("");
 const op=operations.find(x=>x.id===selected)||operations[0]; const effectiveOperation=op?.capability;
 const check=async(nextResources=resources)=>{ if(!effectiveOperation)return; setChecking(true);setError(""); try{ const payload={resources:nextResources}; if(effectiveOperation==="run_hardware_governance")payload.domain=domain; const r=await postJSON("/api/governance/preflight",{operation:effectiveOperation,payload}); setRequired(r.required||[]); setMissing(r.missing||[]); }catch(e){setError(e.message)}finally{setChecking(false)} };
 useEffect(()=>{fetch("/api/resources").then(r=>r.json()).then(data=>{const items=data.items||[];setAvailable(items);const latest={};items.forEach(x=>{if(x.status==="AVAILABLE"&&!latest[x.kind])latest[x.kind]=x});const ids={};Object.keys(latest).forEach(k=>ids[k]=latest[k].resource_id);setResourceRecords(latest);setResources(ids)}).catch(()=>{})},[]);
 useEffect(()=>{setError("");check(resources)},[selected,domain]);
 useEffect(()=>{if(effectiveOperation)check(resources)},[available.length]);
 const uploaded=(kind,data)=>{const next={...resources,[kind]:data.resource_id};setResources(next);setResourceRecords(prev=>({...prev,[kind]:data}));setAvailable(prev=>[data,...prev.filter(x=>x.resource_id!==data.resource_id)]);check(next)};
 const startJob=async()=>{setStarting(true);setError("");try{const payload={resources};if(effectiveOperation==="run_hardware_governance")payload.domain=domain;await postJSON("/api/jobs",{operation:effectiveOperation,payload,actor:"local-user"});setActive("jobs")}catch(e){setError(e.message)}finally{setStarting(false)}};
 const requiredKinds=new Set(required.map(x=>x.kind));
 const displayed=required.length?required:missing;
 return <div className="page"><div className="page-heading"><div><div className="eyebrow">CONTROLLED EXECUTION</div><h1>Reconciliation workspace</h1><p>Required reports are checked before execution. If a report is unavailable, load it here and continue.</p></div><Badge tone={missing.length===0&&!checking?"good":"active"}>{checking?"CHECKING INPUTS":missing.length?"INPUTS REQUIRED":"READY TO RUN"}</Badge></div><div className="workspace"><div className="workspace-nav">{operations.map(o=><button key={o.id} className={selected===o.id?"workspace-link selected":"workspace-link"} onClick={()=>setSelected(o.id)}><strong>{o.name}</strong><small>{o.description}</small></button>)}</div><div className="workspace-body"><div className="callout"><div className="callout-icon"><Icon name="shield"/></div><div><strong>Backend-driven input validation</strong><p>The backend declares the exact report types required for this action. No job starts until every required input is available.</p></div></div>{effectiveOperation==="run_hardware_governance"&&<div className="domain-switch"><span>Governance domain</span><button className={domain==="network"?"selected":""} onClick={()=>setDomain("network")}>Network</button><button className={domain==="server"?"selected":""} onClick={()=>setDomain("server")}>Server</button></div>}<div className="resource-heading"><div><h2>Required input resources</h2><p>{missing.length?"Load "+missing.length+" required file"+(missing.length===1?"":"s")+" to continue.":"All required resources are loaded."}</p></div></div><div className="resource-grid">{displayed.map(item=><ResourceInput key={item.kind} item={item} existing={resourceRecords} onUploaded={uploaded}/>)}</div>{!missing.length&&required.length>0&&<div className="ready-banner"><Icon name="check"/><div><strong>All required reports are loaded</strong><p>The job will use the uploaded files through the V2 service boundary; the V1.4.1 business engine remains unchanged.</p></div></div>}{error&&<div className="form-error">{error}</div>}<div className="run-config"><div><strong>{op?.name}</strong><p>{missing.length?missing.length+" required input"+(missing.length===1?"":"s")+" still needed.":"All inputs satisfied. Ready for controlled execution."}</p></div><button className="primary" disabled={!!missing.length||starting||checking} onClick={startJob}><Icon name="activity"/>{starting?"Starting...":"Start analysis"}</button></div></div></div></div>;
}
function Generic({type}){const c={jobs:["Jobs & runs","Execution state, metrics and output artifacts."],exceptions:["Exceptions","Records requiring human intervention."],audit:["Audit & evidence","Trace recommendations from evidence to governed action."]}[type];return <div className="page"><div className="page-heading"><div><div className="eyebrow">PLATFORM OPERATIONS</div><h1>{c[0]}</h1><p>{c[1]}</p></div><Badge tone="active">LOCAL MODE</Badge></div><div className="empty-enterprise"><div className="empty-icon"><Icon name={type==="audit"?"database":type==="jobs"?"clock":"alert"}/></div><h2>API-ready workspace</h2><p>This surface is intentionally dormant until its domain service is implemented.</p></div></div>}

function App(){
 const [active,setActive]=useState("overview"),[health,setHealth]=useState(null),[operations,setOperations]=useState(fallbackOperations),[jobs,setJobs]=useState([]),[error,setError]=useState("");
 useEffect(()=>{Promise.all([getJSON("/api/health"),getJSON("/api/governance/operations")]).then(([h,o])=>{setHealth(h);setOperations(o.items||fallbackOperations)}).catch(e=>setError(e.message))},[]);
 const page=active==="overview"?<Overview setActive={setActive} operations={operations} health={health}/>:active==="reconciliation"?<Reconciliation operations={operations} setActive={setActive}/>:active==="jobs"?<Jobs jobs={jobs} setJobs={setJobs}/>:active==="governance"?<Generic type="audit"/>:<Generic type={active}/>;
 return <div className="app"><Sidebar active={active} setActive={setActive} health={health}/><main><Header active={active} health={health}/>{error&&<div style={{margin:"12px 32px",padding:"10px",background:"#fff1f2",border:"1px solid #fecdd3",borderRadius:8,fontSize:11}}>API connection: {error}</div>}{page}</main></div>;
}
createRoot(document.getElementById("root")).render(<App />);
